name: video_info_plush
description: "A Dart plugin that provides functionality to extract video IDs from YouTube URLs and retrieve thumbnail images."
version: 1.0.0
homepage: https://github.com/Digvijaysinh2204/video_info_plush
repository: https://github.com/Digvijaysinh2204/video_info_plush
issue_tracker: https://github.com/Digvijaysinh2204/video_info_plush/issues
documentation: https://github.com/Digvijaysinh2204/video_info_plush/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=4.0.0 <8.0.0'
